#!/usr/bin/env bash
# RUSTYPROXY MANAGER (Opção B - EnvironmentFile) - final

set -Eeuo pipefail
IFS=$'\n\t'

PORTS_FILE="/opt/rustyproxy/ports"
PROXY_BIN="/opt/rustyproxy/proxy"

UNIT_TEMPLATE="/etc/systemd/system/proxy@.service"
ENV_DIR="/etc/rustyproxy"

RED="\033[1;31m"
GREEN="\033[1;32m"
YELLOW="\033[1;33m"
BLUE="\033[0;34m"
RESET="\033[0m"

trap 'echo -e "\n${RED}Erro inesperado na linha $LINENO.${RESET}"; exit 1' ERR

if [[ "${EUID}" -ne 0 ]]; then
  echo -e "${RED}Por favor, execute como root (sudo).${RESET}"
  exit 1
fi

[[ -x "${PROXY_BIN}" ]] || { echo -e "${RED}Binário não encontrado/executável: ${PROXY_BIN}${RESET}"; exit 1; }
[[ -f "${UNIT_TEMPLATE}" ]] || { echo -e "${RED}Template systemd não encontrado: ${UNIT_TEMPLATE}${RESET}"; exit 1; }

mkdir -p "$(dirname "$PORTS_FILE")" "$ENV_DIR"
touch "$PORTS_FILE"
chmod 600 "$PORTS_FILE"
chmod 700 "$ENV_DIR"

valid_port() {
  [[ "$1" =~ ^[0-9]+$ ]] || return 1
  (( $1 >= 1 && $1 <= 65535 )) || return 1
}

svc_name() { echo "proxy@${1}.service"; }
env_path() { echo "${ENV_DIR}/proxy${1}.env"; }

is_port_in_use() {
  local port="$1"
  if command -v ss >/dev/null 2>&1; then
    ss -lnt 2>/dev/null | awk '{print $4}' | grep -Eq "(:|\\])${port}$"
    return $?
  fi
  if command -v lsof >/dev/null 2>&1; then
    lsof -iTCP:"$port" -sTCP:LISTEN >/dev/null 2>&1
    return $?
  fi
  return 1
}

# Escreve STATUS de forma segura para EnvironmentFile:
# STATUS='...'
write_env_file() {
  local port="$1"
  local status="$2"
  local p
  p="$(env_path "$port")"

  status="${status//$'\r'/ }"
  status="${status//$'\n'/ }"
  status="${status:0:128}"

  # escape para aspas simples: ' -> '\'' (fecha, escapa, reabre)
  local esc
  esc="$(printf "%s" "$status" | sed "s/'/'\\\\''/g")"

  cat >"$p" <<EOF
# Generated by RustyProxy Manager
STATUS='$esc'
EOF
  chmod 600 "$p"
}

upsert_port_record() {
  local port="$1"
  local status="$2"
  if grep -qE "^${port}\|" "$PORTS_FILE"; then
    sed -i "s/^${port}|.*/${port}|${status}/" "$PORTS_FILE"
  else
    echo "${port}|${status}" >> "$PORTS_FILE"
  fi
}

remove_port_record() {
  local port="$1"
  sed -i "/^${port}\|/d" "$PORTS_FILE" || true
}

add_proxy_port() {
  local port="$1"
  local status="${2:-@RustyManager}"

  valid_port "$port" || { echo -e "${RED}Porta inválida (1-65535).${RESET}"; return; }

  if is_port_in_use "$port"; then
    echo -e "${RED}⛔️ A PORTA $port JÁ ESTÁ EM USO.${RESET}"
    return
  fi

  write_env_file "$port" "$status"

  systemctl enable "$(svc_name "$port")" >/dev/null
  systemctl restart "$(svc_name "$port")"

  upsert_port_record "$port" "$status"
  echo -e "${GREEN}✅ PORTA $port ATIVADA COM SUCESSO.${RESET}"
}

del_proxy_port() {
  local port="$1"
  valid_port "$port" || { echo -e "${RED}Porta inválida (1-65535).${RESET}"; return; }

  systemctl stop "$(svc_name "$port")" >/dev/null 2>&1 || true
  systemctl disable "$(svc_name "$port")" >/dev/null 2>&1 || true

  rm -f "$(env_path "$port")"
  remove_port_record "$port"

  echo -e "${GREEN}✅ PORTA $port DESATIVADA/REMOVIDA COM SUCESSO.${RESET}"
}

update_proxy_status() {
  local port="$1"
  local new_status="$2"

  valid_port "$port" || { echo -e "${RED}Porta inválida (1-65535).${RESET}"; return; }
  [[ -n "${new_status}" ]] || { echo -e "${RED}Status não pode ser vazio.${RESET}"; return; }

  write_env_file "$port" "$new_status"

  # se não existir serviço habilitado ainda, enable+start
  systemctl restart "$(svc_name "$port")" >/dev/null 2>&1 || {
    systemctl enable "$(svc_name "$port")" >/dev/null
    systemctl restart "$(svc_name "$port")"
  }

  upsert_port_record "$port" "$new_status"
  echo -e "${YELLOW}🔃 STATUS DA PORTA $port ATUALIZADO PARA '${new_status}'.${RESET}"
  sleep 1
}

restart_all_proxies() {
  if [[ ! -s "$PORTS_FILE" ]]; then
    echo "NENHUMA PORTA ENCONTRADA PARA REINICIAR."
    return
  fi

  echo "🔃 REINICIANDO TODAS AS PORTAS DO PROXY..."
  sleep 1

  while IFS='|' read -r port status; do
    [[ -n "${port:-}" ]] || continue
    valid_port "$port" || continue

    # garante env consistente
    write_env_file "$port" "${status:-@RustyManager}"

    systemctl restart "$(svc_name "$port")" >/dev/null 2>&1 || {
      systemctl enable "$(svc_name "$port")" >/dev/null
      systemctl restart "$(svc_name "$port")"
    }
  done < "$PORTS_FILE"

  echo -e "${GREEN}✅ TODAS AS PORTAS FORAM REINICIADAS COM SUCESSO.${RESET}"
  sleep 1
}

uninstall_rustyproxy() {
  echo -e "${YELLOW}🗑️ DESINSTALANDO RUSTY PROXY, AGUARDE...${RESET}"
  sleep 1
  clear

  # Para tudo que estiver listado
  if [[ -s "$PORTS_FILE" ]]; then
    while IFS='|' read -r port _; do
      [[ -n "${port:-}" ]] || continue
      valid_port "$port" || continue
      systemctl stop "$(svc_name "$port")" >/dev/null 2>&1 || true
      systemctl disable "$(svc_name "$port")" >/dev/null 2>&1 || true
      rm -f "$(env_path "$port")"
    done < "$PORTS_FILE"
  fi

  # Remove envs órfãos e template (instalado pelo install.sh)
  rm -rf "$ENV_DIR" || true
  rm -f "$UNIT_TEMPLATE" || true
  systemctl daemon-reload

  rm -rf /opt/rustyproxy
  rm -f /usr/local/bin/rustyproxy /usr/local/bin/rustyproxyctl || true

  echo -e "\033[0;36m┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\033[0m"
  echo -e "\033[1;36m┃\E[44;1;37m RUSTY PROXY DESINSTALADO COM SUCESSO. \E[0m\033[0;36m┃"
  echo -e "\033[0;36m┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛\033[0m"
  sleep 2
  clear
  exit 0
}

show_menu() {
  clear
  echo -e "\033[1;36m┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\033[0m"
  echo -e "\033[1;36m┃\E[44;1;37m              MULTI-PROXY              \E[0m\033[0;36m┃"
  echo -e "\033[1;36m┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫\033[0m"
  echo -e "\033[1;36m┃\033[1;33mGERENCIAMENTO DE PORTAS - MULTI-PROXY  \033[1;36m┃\033[0m"
  echo -e "\033[1;36m┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫\033[0m"

  if [[ -s "$PORTS_FILE" ]]; then
    active_ports="$(cut -d'|' -f1 "$PORTS_FILE" | paste -sd ' ' -)"
    echo -e "\033[1;36m┃\033[1;33mPORTAS ATIVAS:\033[1;33m $(printf '%-21s' "$active_ports")   \033[1;36m┃\033[0m"
  else
    echo -e "\033[1;36m┃\033[1;33mPORTAS ATIVAS:\033[1;33m (nenhuma)                 \033[1;36m┃\033[0m"
  fi

  echo -e "\033[1;36m┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫\033[0m"
  echo -e "\033[1;36m┃\033[1;31m[\033[1;34m01\033[1;31m] \033[1;37m◉ \033[1;33mATIVAR PROXY                    \033[1;36m┃\033[0m"
  echo -e "\033[1;36m┃\033[1;31m[\033[1;34m02\033[1;31m] \033[1;37m◉ \033[1;33mDESATIVAR PROXY                 \033[1;36m┃\033[0m"
  echo -e "\033[1;36m┃\033[1;31m[\033[1;34m03\033[1;31m] \033[1;37m◉ \033[1;33mREINICIAR PROXIES               \033[1;36m┃\033[0m"
  echo -e "\033[1;36m┃\033[1;31m[\033[1;34m04\033[1;31m] \033[1;37m◉ \033[1;33mALTERAR STATUS                  \033[1;36m┃\033[0m"
  echo -e "\033[1;36m┃\033[1;31m[\033[1;34m05\033[1;31m] \033[1;37m◉ \033[1;33mDESINSTALAR SCRIPT              \033[1;36m┃\033[0m"
  echo -e "\033[1;36m┃\033[1;31m[\033[1;34m00\033[1;31m] \033[1;37m◉ \033[1;33mSAIR DO MENU                    \033[1;36m┃\033[0m"
  echo -e "\033[1;36m┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛\033[0m"

  read -r -p "┗━➤ SELECIONE UMA OPÇÃO: " option

  case "$option" in
    1)
      clear
      read -r -p "━➤ DIGITE A PORTA (1-65535): " port
      until valid_port "$port"; do
        echo "━➤ DIGITE UMA PORTA VÁLIDA (1-65535)."
        read -r -p "━➤ DIGITE A PORTA (1-65535): " port
      done
      read -r -p "━➤ DIGITE UM STATUS (pode ter espaços): " status
      [[ -n "${status}" ]] || status="@RustyManager"
      add_proxy_port "$port" "$status"
      read -r -p "━➤ OK. PRESSIONE ENTER." dummy
      ;;
    2)
      clear
      read -r -p "━➤ DIGITE A PORTA (1-65535): " port
      until valid_port "$port"; do
        echo "━➤ DIGITE UMA PORTA VÁLIDA (1-65535)."
        read -r -p "━➤ DIGITE A PORTA (1-65535): " port
      done
      del_proxy_port "$port"
      read -r -p "━➤ OK. PRESSIONE ENTER." dummy
      ;;
    3)
      clear
      restart_all_proxies
      read -r -p "━➤ OK. PRESSIONE ENTER." dummy
      ;;
    4)
      clear
      read -r -p "━➤ DIGITE A PORTA (1-65535): " port
      until valid_port "$port"; do
        echo "━➤ DIGITE UMA PORTA VÁLIDA (1-65535)."
        read -r -p "━➤ DIGITE A PORTA (1-65535): " port
      done
      read -r -p "━➤ DIGITE O NOVO STATUS (pode ter espaços): " new_status
      update_proxy_status "$port" "$new_status"
      read -r -p "━➤ OK. PRESSIONE ENTER." dummy
      ;;
    5)
      clear
      uninstall_rustyproxy
      ;;
    0)
      clear
      exit 0
      ;;
    *)
      echo "OPÇÃO INVÁLIDA. PRESSIONE ENTER PARA VOLTAR."
      read -r dummy
      ;;
  esac
}

while true; do
  show_menu
done
